spring.datasource.url=jdbc:postgresql://localhost:5432/spring_hospital
spring.datasource.username=postgres
spring.datasource.password=14768967Lyceum

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.security.user.name=admin
spring.security.user.password=admin